# Generated by Django 4.0 on 2022-08-15 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_task_row_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
