# Generated by Django 4.0 on 2022-08-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_entry_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sheets.task'),
        ),
    ]
