# Generated by Django 4.0 on 2022-08-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='genre',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
