# Generated by Django 4.0 on 2022-08-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_task_genre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('task', 'date')},
        ),
    ]
